# Generated by Django 3.2.7 on 2021-11-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_scriptactivity_lessonid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSign',
            fields=[
                ('callsignid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('frame', models.ImageField(upload_to='frames/')),
                ('exrequired', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateField(auto_now_add=True, null=True)),
                ('editdate', models.DateTimeField(auto_now=True, null=True)),
                ('isenable', models.BooleanField(blank=True, default=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CallSign',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gameorder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lessonorder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='scriptactivity',
            old_name='scriptorder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='topiclesson',
            old_name='topicorder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='topicpractice',
            old_name='topicorder',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rankid',
        ),
        migrations.RemoveField(
            model_name='scriptactivity',
            name='activityid',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.AddField(
            model_name='account',
            name='callsignid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.callsign'),
        ),
    ]
