# Generated by Django 3.2.7 on 2021-11-05 06:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20211105_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('scriptactivityid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('activityorder', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateField(auto_now_add=True, null=True)),
                ('editdate', models.DateTimeField(auto_now=True, null=True)),
                ('isenable', models.BooleanField(blank=True, default=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Activity',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='ScriptActivity',
        ),
        migrations.RenameField(
            model_name='callsign',
            old_name='order',
            new_name='callsignorder',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='order',
            new_name='gameorder',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='order',
            new_name='lessonorder',
        ),
        migrations.RenameField(
            model_name='topiclesson',
            old_name='order',
            new_name='topicorder',
        ),
        migrations.RenameField(
            model_name='topicpractice',
            old_name='order',
            new_name='topicorder',
        ),
        migrations.AddField(
            model_name='activity',
            name='lessonid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.lesson'),
        ),
    ]
