# Generated by Django 3.2.7 on 2021-11-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20211105_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='scriptactivityid',
            new_name='activityid',
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='practice-games/images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/images'),
        ),
    ]
