# Generated by Django 3.2.7 on 2021-11-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='faq',
            table='FAQ',
        ),
    ]
