# Generated by Django 3.2.7 on 2021-11-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
    ]
