# Generated by Django 3.2.7 on 2021-11-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_delete_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
