# Generated by Django 3.2.7 on 2021-11-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_activity_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
