# Generated by Django 3.2.7 on 2021-11-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('trackingid', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateField(auto_now_add=True, null=True)),
                ('editdate', models.DateTimeField(auto_now=True, null=True)),
                ('isenable', models.BooleanField(blank=True, default=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('accountid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.account')),
                ('activityid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.activity')),
            ],
            options={
                'db_table': 'Tracking',
                'managed': True,
            },
        ),
    ]
