# Generated by Django 3.2.7 on 2021-12-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_auto_20211230_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevel',
            name='levelorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
