# Generated by Django 3.2.7 on 2022-01-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_gamelevel_levelorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLevelGame',
            fields=[
                ('trackinglevelid', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateField(auto_now_add=True, null=True)),
                ('editdate', models.DateTimeField(auto_now=True, null=True)),
                ('isenable', models.BooleanField(blank=True, default=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('accountid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.account')),
                ('gameid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.game')),
                ('levelid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.gamelevel')),
            ],
            options={
                'db_table': 'TrackingLevelGame',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='TrackingGame',
        ),
    ]
