# Generated by Django 3.2.7 on 2022-01-01 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_trackinglevelgame_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingactivity',
            name='lessonid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.lesson'),
        ),
        migrations.AddField(
            model_name='trackingactivity',
            name='topiclessonid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.topiclesson'),
        ),
    ]
