# Generated by Django 3.1.13 on 2022-01-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_auto_20220102_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
